# Generated by Django 4.1.6 on 2023-02-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormPractice_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
